2024-09-26 18:03:59,530 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\ProjectPy\lessonPy\Module12\home_work12_4.py", line 24, in test_run
    greyhound = rt_with_exceptions.Runner(2)
  File "D:\ProjectPy\lessonPy\Module12\rt_with_exceptions.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-26 18:03:59,531 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\ProjectPy\lessonPy\Module12\home_work12_4.py", line 13, in test_walk
    horse = rt_with_exceptions.Runner('Вася', -2)
  File "D:\ProjectPy\lessonPy\Module12\rt_with_exceptions.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
